# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14fzlyutOoaGDbgsOh6TjRTdueThUtlbh

# Zadanie 1

**Budowa pipeline ETL dla danych sprzedaży**

Extract – wczytanie danych

Transform – czyszczenie i przygotowanie

Load – zapis danych

# Extract
"""

import pandas as pd

df = pd.read_csv("Online_Retail.csv", encoding="latin1")

df.head()
df.info()
df.describe()

"""# Transform

**Usunięcie brakujących CustomerID**
"""

df = df.dropna(subset=["CustomerID"])

"""**Usunięcie złych wartości**

Quantity <= 0
"""

df = df[df["Quantity"] > 0]

"""UnitPrice < 0"""

df = df[df["UnitPrice"] >= 0]

"""**Usunięcie duplikatów**"""

df = df.drop_duplicates()

"""**Poprawienie typu danych**"""

df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])
df["CustomerID"] = df["CustomerID"].astype(int)

"""**Rozbicie daty**"""

df = df.dropna(subset=["InvoiceDate"])

df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

df["Year"] = df["InvoiceDate"].dt.year
df["Month"] = df["InvoiceDate"].dt.month
df["Day"] = df["InvoiceDate"].dt.day

"""**Sprawdzenie po czyszczeniu**"""

df.head()

"""**Jak przygotować dane, aby łatwo analizować wartość sprzedaży i przychód?**

Dane należy przygotować poprzez dodanie nowej kolumny Revenue, obliczonej jako iloczyn liczby produktów (Quantity) oraz ceny jednostkowej (UnitPrice). Dzięki temu możliwa jest bezpośrednia analiza wartości sprzedaży.

**Czy potrzebne są dodatkowe kolumny?**

Tak, konieczne jest dodanie kolumny Revenue, która reprezentuje wartość transakcji. Dodatkowo można rozważyć utworzenie kolumny łączącej rok i miesiąc (np. YearMonth) w celu analizy czasowej.

**Czy warto coś policzyć już na etapie ETL?**

Tak, warto obliczyć podstawowe miary, takie jak przychód (Revenue), już na etapie ETL, ponieważ:

upraszcza to późniejszą analizę danych

eliminuje konieczność wielokrotnego liczenia tych samych wartości

poprawia czytelność i użyteczność zbioru danych

**Utworzenie tabeli faktów**
"""

fact_table = df[[
    "InvoiceNo",
    "StockCode",
    "CustomerID",
    "InvoiceDate",
    "Quantity",
]]

"""# Load

**Eksport tabeli faktów do pliku CSV**
"""

fact_table.to_csv("fact_sales.csv", index=False)

"""# Zadanie 2

**Wczytanie zbiorów danych**
"""

df1 = pd.read_csv("Online_Retail.csv", encoding="latin1")
df2 = pd.read_excel("online_retail_II.xlsx")

"""**Porównanie zbiorów**"""

df1.columns
df2.columns

df1.dtypes
df2.dtypes

df1.isnull().sum()
df2.isnull().sum()

"""**Czy struktura danych jest identyczna?**

Nie, struktura danych nie jest identyczna. Występują różnice w nazwach kolumn (np. CustomerID vs Customer ID, InvoiceNo vs Invoice, UnitPrice vs Price) oraz w liczbie brakujących wartości.

**Czy dane można od razu połączyć?**

Nie, danych nie można od razu połączyć. Przed połączeniem należy:

ujednolicić nazwy kolumn

upewnić się, że typy danych są zgodne

obsłużyć brakujące wartości

**Ujednolicenie nazw kolumn**
"""

df2 = df2.rename(columns={
    "Invoice": "InvoiceNo",
    "Customer ID": "CustomerID",
    "Price": "UnitPrice"
})

"""**Ujednolicenie typów danych**"""

df1["CustomerID"] = df1["CustomerID"].astype("Int64")
df2["CustomerID"] = df2["CustomerID"].astype("Int64")

"""**Ujednolicenie dat**"""

df1["InvoiceDate"] = pd.to_datetime(df1["InvoiceDate"])
df2["InvoiceDate"] = pd.to_datetime(df2["InvoiceDate"])

"""**Połączenie danych**"""

df = pd.concat([df1, df2], ignore_index=True)

"""**Który schemat przyjąć jako docelowy?**

Jako schemat docelowy należy przyjąć strukturę pierwszego zbioru danych (df1), ponieważ zawiera spójne nazwy kolumn bez spacji oraz bardziej standardowe nazewnictwo.

**Czy wszystkie kolumny są potrzebne?**

Nie, nie wszystkie kolumny są konieczne. Do analizy sprzedaży wystarczą kluczowe kolumny, takie jak:

InvoiceNo

StockCode

CustomerID

InvoiceDate

Quantity

UnitPrice

Pozostałe kolumny mogą być opcjonalne w zależności od analizy.

# Data Quality

**Wykrywanie duplikatów**
"""

duplicates = df[df.duplicated(subset=[
    "InvoiceNo", "StockCode", "CustomerID", "InvoiceDate"
])]

"""**Wykrywanie niespójności**"""

df.groupby("StockCode")["UnitPrice"].nunique().sort_values(ascending=False)

"""**Jak rozpoznać duplikat?**

Duplikaty można rozpoznać na podstawie identycznych wartości w kluczowych kolumnach, takich jak InvoiceNo, StockCode, CustomerID oraz InvoiceDate.

**Co zrobić z konfliktem danych?**

W przypadku konfliktów danych należy:

wybrać jedną wartość

lub usunąć niejednoznaczne rekordy

**Które źródło jest bardziej wiarygodne?**

Bardziej wiarygodne jest źródło, które:

zawiera mniej brakujących wartości

ma spójniejsze dane

jest bardziej aktualne i kompletne

# Merge
"""

df_all = pd.concat([df1, df2], ignore_index=True)

"""**Czy użyć concat czy merge?**

Należy użyć funkcji concat, ponieważ oba zbiory danych mają tę samą strukturę i chcemy je połączyć jeden pod drugim.

Funkcja merge służy do łączenia danych na podstawie wspólnych kolumn, co w tym przypadku nie jest potrzebne.

**Czy zachować wszystkie rekordy?**

Tak, należy zachować wszystkie rekordy, aby nie utracić żadnych informacji.
Ewentualne duplikaty lub błędne dane można usunąć na etapie czyszczenia danych.

# Load

**Zapis zintegrowanych danych**
"""

fact_table.to_csv("fact_sales_integrated.csv", index=False)